import React, { useState } from 'react';
import { ActivityIndicator, Alert, Image, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import api from '../utils/api';

export default function FoodScanScreen({ onNavigate }) {
  const [image, setImage] = useState(null); const [items, setItems] = useState([]); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false);
  const choose = async (camera) => { const permission = camera ? await ImagePicker.requestCameraPermissionsAsync() : await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert('Permission needed', 'Allow access to scan a food photo.'); const result = camera ? await ImagePicker.launchCameraAsync({ mediaTypes:['images'], quality:0.7 }) : await ImagePicker.launchImageLibraryAsync({ mediaTypes:['images'], quality:0.7 }); if (!result.canceled) { setImage(result.assets[0]); setItems([]); } };
  const scan = async () => { if (!image) return Alert.alert('Choose a photo first'); setLoading(true); try { const data = new FormData(); data.append('image', { uri:image.uri, name:image.fileName || 'meal.jpg', type:image.mimeType || 'image/jpeg' }); const response = await api.post('/food/scan', data, { headers:{ 'Content-Type':'multipart/form-data' } }); setItems(response.data.items.map(item => ({ ...item, mealType:'snack' }))); } catch (error) { Alert.alert('Could not scan photo', error.response?.data?.message || 'Please add the meal manually.'); } finally { setLoading(false); } };
  const update = (index, key, value) => setItems(items.map((item, i) => i === index ? {...item, [key]:value} : item));
  const save = async () => { if (!items.length) return; setSaving(true); try { await Promise.all(items.filter(item => item.name).map(({ servingGrams, confidence, ...meal }) => api.post('/meals', meal))); Alert.alert('Saved', `${items.length} meal item(s) added to today.`); onNavigate('nutrition'); } catch (error) { Alert.alert('Could not save', error.response?.data?.message || 'Try again.'); } finally { setSaving(false); } };
  return <ScrollView contentContainerStyle={s.page}><View style={s.header}><Text style={s.title}>Scan food</Text><TouchableOpacity onPress={() => onNavigate('nutrition')}><Text style={s.link}>Cancel</Text></TouchableOpacity></View><Text style={s.copy}>AI estimates food and portions. Review every item before saving.</Text>{image && <Image source={{uri:image.uri}} style={s.image}/>}<View style={s.row}><TouchableOpacity style={s.secondary} onPress={() => choose(true)}><Text style={s.buttonText}>Camera</Text></TouchableOpacity><TouchableOpacity style={s.secondary} onPress={() => choose(false)}><Text style={s.buttonText}>Gallery</Text></TouchableOpacity></View><TouchableOpacity style={s.primary} onPress={scan} disabled={loading}>{loading ? <ActivityIndicator color="#fff"/> : <Text style={s.buttonText}>Analyze photo</Text>}</TouchableOpacity>{items.map((item,index) => <View style={s.card} key={`${item.name}-${index}`}><TextInput style={s.name} value={item.name} onChangeText={v=>update(index,'name',v)}/><Text style={s.small}>Estimated {item.servingGrams}g · confidence {Math.round(item.confidence*100)}%</Text><View style={s.row}>{['calories','protein','carbs','fats'].map(key=><View style={s.field} key={key}><Text style={s.label}>{key}</Text><TextInput style={s.input} value={String(item[key])} keyboardType="decimal-pad" onChangeText={v=>update(index,key,v)}/></View>)}</View><TouchableOpacity onPress={()=>setItems(items.filter((_,i)=>i!==index))}><Text style={s.remove}>Remove item</Text></TouchableOpacity></View>)}{items.length > 0 && <TouchableOpacity style={s.primary} onPress={save} disabled={saving}>{saving ? <ActivityIndicator color="#fff"/> : <Text style={s.buttonText}>Confirm and save</Text>}</TouchableOpacity>}</ScrollView>;
}
const s=StyleSheet.create({page:{backgroundColor:'#0f172a',padding:20,flexGrow:1},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{color:'#fff',fontSize:28,fontWeight:'800'},link:{color:'#38bdf8'},copy:{color:'#94a3b8',lineHeight:20,marginVertical:16},image:{height:220,borderRadius:16,width:'100%',marginBottom:12},row:{flexDirection:'row',gap:8},primary:{backgroundColor:'#10b981',padding:15,borderRadius:14,alignItems:'center',marginTop:12},secondary:{flex:1,backgroundColor:'#1e293b',padding:14,borderRadius:14,alignItems:'center'},buttonText:{color:'#fff',fontWeight:'800'},card:{backgroundColor:'#1e293b',borderRadius:14,padding:14,marginTop:14},name:{color:'#fff',fontSize:17,fontWeight:'700',borderBottomWidth:1,borderColor:'#334155',paddingBottom:6},small:{color:'#94a3b8',marginVertical:9},field:{flex:1},label:{color:'#94a3b8',fontSize:11,textTransform:'uppercase'},input:{backgroundColor:'#0f172a',color:'#fff',borderRadius:8,padding:8,marginTop:4},remove:{color:'#f87171',fontWeight:'700',marginTop:12}});
