import React, { useMemo, useState } from 'react';
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import api from '../utils/api';

const formatDate = days => new Date(Date.now() + days * 86400000).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric' });
const daysFor = (kg, adjustment) => Math.ceil((Math.abs(kg) * 7700) / Math.abs(adjustment));

export default function GoalPlanScreen({ onNavigate, screenData }) {
  const user = screenData?.user || {};
  const current = Number(user.currentWeight || 0); const target = Number(user.targetWeight || 0); const height = Number(user.height || 0);
  const difference = target - current; const direction = difference < -0.05 ? 'loss' : difference > 0.05 ? 'gain' : 'maintenance';
  const bmi = height ? Number((current / ((height / 100) ** 2)).toFixed(1)) : 0;
  const plans = useMemo(() => direction === 'loss' ? [
    { id:'loss-gentle', label:'Gentle cut', adjustment:-250, note:'Smaller food deficit, slower pace' },
    { id:'loss-balanced', label:'Balanced cut', adjustment:-450, note:'Balanced diet and activity plan' },
    { id:'loss-focused', label:'Focused cut', adjustment:-650, note:'Higher deficit; choose only if sustainable' },
  ] : direction === 'gain' ? [
    { id:'gain-steady', label:'Steady gain', adjustment:200, note:'Small calorie surplus for gradual gain' },
    { id:'gain-balanced', label:'Balanced gain', adjustment:350, note:'Moderate surplus with strength training' },
    { id:'gain-focused', label:'Focused gain', adjustment:500, note:'Larger surplus; review progress regularly' },
  ] : [{ id:'maintenance', label:'Maintain weight', adjustment:0, note:'Eat around your TDEE to maintain weight' }], [direction]);
  const [selected, setSelected] = useState(user.goalPlan?.id || plans[1]?.id || plans[0].id); const [saving, setSaving] = useState(false);
  const targetBmi = height ? Number((target / ((height / 100) ** 2)).toFixed(1)) : 0;
  const choose = plans.find(p => p.id === selected) || plans[0]; const days = choose.adjustment ? daysFor(difference, choose.adjustment) : 0;
  const save = async () => { setSaving(true); try { const response = await api.put('/user/biometrics', { goalPlan: { ...choose, dailyAdjustment: choose.adjustment } }); const updated = response.data.user; await AsyncStorage.setItem('user', JSON.stringify(updated)); onNavigate('dashboard', { user:updated, biometrics:response.data.biometrics }); } catch (error) { Alert.alert('Could not save plan', error.response?.data?.message || 'Try again.'); } finally { setSaving(false); } };
  return <ScrollView contentContainerStyle={s.page}><Text style={s.title}>Choose your goal plan</Text><Text style={s.sub}>We use your weight goal and TDEE to set your daily food budget.</Text><View style={s.summary}><Text style={s.summaryTitle}>{direction === 'loss' ? `Lose ${Math.abs(difference).toFixed(1)} kg` : direction === 'gain' ? `Gain ${Math.abs(difference).toFixed(1)} kg` : 'Maintain your current weight'}</Text><Text style={s.summaryText}>BMI now: {bmi} · Target BMI: {targetBmi}</Text></View>{direction === 'loss' && targetBmi > 0 && targetBmi < 18.5 && <View style={s.warning}><Text style={s.warningText}>Your target is below the standard adult BMI healthy range. Consider discussing this goal with a qualified health professional before choosing a deficit.</Text></View>}{plans.map(plan => { const active=plan.id===selected; const planDays=plan.adjustment ? daysFor(difference,plan.adjustment) : 0; return <TouchableOpacity key={plan.id} style={[s.card,active&&s.active]} onPress={()=>setSelected(plan.id)}><View style={s.cardHeader}><Text style={s.cardTitle}>{plan.label}</Text><Text style={s.adjustment}>{plan.adjustment > 0 ? '+' : ''}{plan.adjustment} kcal/day</Text></View><Text style={s.note}>{plan.note}</Text>{planDays > 0 && <Text style={s.timeline}>Estimated target date: {formatDate(planDays)} · about {Math.ceil(planDays / 7)} weeks</Text>}</TouchableOpacity>})}<View style={s.budget}><Text style={s.budgetLabel}>DAILY FOOD BUDGET</Text><Text style={s.budgetValue}>{Math.max(1200, Math.round(Number(user.tdee || 0) + choose.adjustment))} kcal</Text><Text style={s.note}>TDEE {user.tdee || '—'} kcal {choose.adjustment ? `· ${Math.abs(choose.adjustment)} kcal/day ${choose.adjustment < 0 ? 'deficit' : 'surplus'}` : ''}</Text></View><TouchableOpacity style={s.button} onPress={save} disabled={saving}>{saving?<ActivityIndicator color="#fff"/>:<Text style={s.buttonText}>Use this plan</Text>}</TouchableOpacity></ScrollView>;
}
const s=StyleSheet.create({page:{flexGrow:1,backgroundColor:'#0f172a',padding:20},title:{color:'#fff',fontSize:28,fontWeight:'800'},sub:{color:'#94a3b8',lineHeight:20,marginTop:7,marginBottom:16},summary:{backgroundColor:'#1e293b',borderRadius:16,padding:16,marginBottom:12},summaryTitle:{color:'#fff',fontSize:19,fontWeight:'800'},summaryText:{color:'#94a3b8',marginTop:5},warning:{backgroundColor:'rgba(245,158,11,.14)',borderColor:'#f59e0b',borderWidth:1,borderRadius:14,padding:14,marginBottom:12},warningText:{color:'#fcd34d',lineHeight:19},card:{backgroundColor:'#1e293b',borderColor:'#334155',borderWidth:1,borderRadius:16,padding:16,marginBottom:10},active:{borderColor:'#10b981',backgroundColor:'rgba(16,185,129,.13)'},cardHeader:{flexDirection:'row',justifyContent:'space-between',gap:8},cardTitle:{color:'#fff',fontSize:17,fontWeight:'800'},adjustment:{color:'#10b981',fontWeight:'800'},note:{color:'#94a3b8',marginTop:7,lineHeight:18},timeline:{color:'#38bdf8',fontSize:12,fontWeight:'700',marginTop:12},budget:{backgroundColor:'#1e293b',borderRadius:16,padding:18,marginTop:7},budgetLabel:{color:'#94a3b8',fontSize:11,fontWeight:'800'},budgetValue:{color:'#10b981',fontSize:31,fontWeight:'800',marginTop:5},button:{backgroundColor:'#10b981',padding:16,borderRadius:14,alignItems:'center',marginVertical:18},buttonText:{color:'#fff',fontWeight:'800',fontSize:16}});
