import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Modal, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import api from '../utils/api';

const empty = { name: '', mealType: 'snack', calories: '', protein: '', carbs: '', fats: '' };
export default function NutritionScreen({ onNavigate }) {
  const [meals, setMeals] = useState([]); const [form, setForm] = useState(empty); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { setLoading(true); setMeals((await api.get('/meals')).data.meals); } catch { Alert.alert('Could not load meals', 'Check that the API server is running and your API URL is configured.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const save = async () => { if (!form.name || !form.calories) return Alert.alert('Missing details', 'A name and calories are required.'); try { await api.post('/meals', form); setForm(empty); setOpen(false); load(); } catch (e) { Alert.alert('Could not save meal', e.response?.data?.message || 'Try again.'); } };
  const remove = id => Alert.alert('Delete meal?', 'This cannot be undone.', [{ text: 'Cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { await api.delete(`/meals/${id}`); load(); } }]);
  const total = meals.reduce((sum, meal) => sum + meal.calories, 0);
  return <View style={s.page}><View style={s.header}><Text style={s.title}>Nutrition</Text><TouchableOpacity onPress={() => onNavigate('dashboard')}><Text style={s.link}>Dashboard</Text></TouchableOpacity></View><Text style={s.summary}>{total} kcal logged today</Text>{loading ? <ActivityIndicator color="#10b981" /> : <FlatList data={meals} keyExtractor={m => m._id} ListEmptyComponent={<Text style={s.empty}>No meals yet. Add your first meal.</Text>} renderItem={({ item }) => <TouchableOpacity style={s.card} onLongPress={() => remove(item._id)}><View><Text style={s.name}>{item.name}</Text><Text style={s.meta}>{item.mealType} · P {item.protein}g · C {item.carbs}g · F {item.fats}g</Text></View><Text style={s.cal}>{item.calories} kcal</Text></TouchableOpacity>} /> }<TouchableOpacity style={s.secondaryAdd} onPress={() => onNavigate('food-scan')}><Text style={s.addText}>⌁ Scan food photo</Text></TouchableOpacity><TouchableOpacity style={s.add} onPress={() => setOpen(true)}><Text style={s.addText}>+ Add meal manually</Text></TouchableOpacity><Modal visible={open} animationType="slide"><View style={s.modal}>{Object.keys(form).map(key => key === 'mealType' ? <View key={key} style={s.types}>{['breakfast','lunch','dinner','snack'].map(type => <TouchableOpacity key={type} style={[s.type, form.mealType === type && s.selected]} onPress={() => setForm({...form, mealType:type})}><Text style={s.typeText}>{type}</Text></TouchableOpacity>)}</View> : <TextInput key={key} style={s.input} placeholder={key} placeholderTextColor="#64748b" value={form[key]} keyboardType={key === 'name' ? 'default' : 'decimal-pad'} onChangeText={v => setForm({...form,[key]:v})}/>)}<TouchableOpacity style={s.add} onPress={save}><Text style={s.addText}>Save meal</Text></TouchableOpacity><TouchableOpacity onPress={() => setOpen(false)}><Text style={s.cancel}>Cancel</Text></TouchableOpacity></View></Modal></View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0f172a',padding:20},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{color:'#fff',fontSize:28,fontWeight:'800'},link:{color:'#38bdf8'},summary:{color:'#10b981',fontSize:18,fontWeight:'700',marginVertical:18},card:{backgroundColor:'#1e293b',padding:16,borderRadius:14,marginBottom:10,flexDirection:'row',justifyContent:'space-between'},name:{color:'#fff',fontSize:16,fontWeight:'700'},meta:{color:'#94a3b8',marginTop:4},cal:{color:'#f59e0b',fontWeight:'700'},empty:{color:'#94a3b8',textAlign:'center',marginTop:50},add:{backgroundColor:'#10b981',padding:16,borderRadius:14,alignItems:'center',marginTop:12},secondaryAdd:{backgroundColor:'#0f766e',padding:16,borderRadius:14,alignItems:'center',marginTop:12},addText:{color:'#fff',fontWeight:'800'},modal:{flex:1,backgroundColor:'#0f172a',padding:24,justifyContent:'center'},input:{backgroundColor:'#1e293b',color:'#fff',padding:14,borderRadius:12,marginVertical:5},types:{flexDirection:'row',flexWrap:'wrap',gap:6,marginVertical:12},type:{padding:10,backgroundColor:'#1e293b',borderRadius:10},selected:{backgroundColor:'#10b981'},typeText:{color:'#fff'},cancel:{color:'#94a3b8',textAlign:'center',marginTop:18}});
