import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import api from '../utils/api';

const labelDate = value => new Date(`${value}T12:00:00`).toLocaleDateString(undefined, { weekday: 'short', day: 'numeric', month: 'short' });
export default function ProgressScreen({ onNavigate }) {
  const [history, setHistory] = useState([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { setLoading(true); setHistory((await api.get('/dashboard/history?days=14')).data.history.reverse()); } catch (error) { console.log('History error:', error.message); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const totals = history.reduce((sum, day) => ({ calories: sum.calories + day.calories, burned: sum.burned + day.caloriesBurned }), { calories: 0, burned: 0 });
  return <View style={s.page}><View style={s.header}><Text style={s.title}>Progress</Text><TouchableOpacity onPress={() => onNavigate('dashboard')}><Text style={s.link}>Dashboard</Text></TouchableOpacity></View><Text style={s.sub}>Your last 14 calendar days</Text>{loading && !history.length ? <ActivityIndicator color="#10b981" style={{marginTop:40}}/> : <FlatList data={history} keyExtractor={item=>item.date} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor="#10b981"/>} ListHeaderComponent={<View style={s.total}><Text style={s.totalTitle}>{totals.calories} kcal eaten</Text><Text style={s.totalSub}>{totals.burned} kcal burned across recorded days</Text></View>} renderItem={({item}) => { const over = item.difference > 0; const hasData = item.calories > 0 || item.caloriesBurned > 0 || item.steps > 0; return <View style={s.card}><View><Text style={s.date}>{labelDate(item.date)}</Text><Text style={s.detail}>{item.calories} / {item.target} kcal eaten</Text></View><View style={s.right}><Text style={[s.status, over && s.over]}>{over ? `${item.difference} over` : `${Math.abs(item.difference)} left`}</Text><Text style={s.detail}>{hasData ? `${item.caloriesBurned} burned · ${item.steps} steps` : 'No activity logged'}</Text></View></View>; }} ListEmptyComponent={<Text style={s.empty}>No history yet. Save meals to start your calendar history.</Text>}/>}</View>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0f172a',padding:20},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},title:{fontSize:28,fontWeight:'800',color:'#fff'},link:{color:'#38bdf8'},sub:{color:'#94a3b8',marginTop:6,marginBottom:14},total:{backgroundColor:'#1e293b',borderRadius:16,padding:17,marginBottom:12},totalTitle:{color:'#10b981',fontSize:23,fontWeight:'800'},totalSub:{color:'#94a3b8',marginTop:4},card:{backgroundColor:'#1e293b',borderRadius:14,padding:15,marginBottom:9,flexDirection:'row',justifyContent:'space-between'},date:{color:'#fff',fontWeight:'800',fontSize:16},detail:{color:'#94a3b8',fontSize:12,marginTop:5},right:{alignItems:'flex-end'},status:{color:'#10b981',fontWeight:'800'},over:{color:'#f87171'},empty:{color:'#94a3b8',textAlign:'center',marginTop:50}});
